language:
  - cpp

matrix:
  include:
    - os: linux
    - os: osx

sudo: enabled

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libboost-all-dev; fi
  - if [ $TRAVIS_OS_NAME = osx ];  then brew install boost; fi
 sudo apt-get install libboost-all-dev

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ./unit_test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
