sudo: false

language:
  - cpp

os:
  - linux
      sudo: required
#  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get install libboost-all-dev

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ./unit_test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
