sudo: false

language:
  - cpp

matrix:
 include:
  - os: linux
    compiler: gcc
    env: 
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - os: linux
    compiler: clang
    env: 
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang

before_install:
  - pushd .
  - pip install --user cpp-coveralls
  - echo $PWD
  - PRJ=$PWD
  - mkdir -p build/boost/
  - cd build/boost/
  - wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
  - tar -xvf boost_1_65_1.tar.gz
  - cd boost_1_65_1
  - ./bootstrap.sh --prefix=$PRJ/build/boost/
  - ./b2 cxxflags='-std=c++11'
  - ./b2 install
  - popd


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
